### ISSUE TITLE
Missing parts in your tutorial

### ISSUE THREAD

**Issue by Fede2782** [ravindu644/Android-Kernel-Tutorials#1]
Unfortunately many Samsung devices have kernel sources which don't build (for example Tab S6 Lite) or have missing parts (like Connectivity drivers for Mediatek), even using Samsung listed toolchains. You should list these warnings. Have a good day!

**Comment by ravindu644** [comment]
Yes. You are right.

Most of the samsung kernel sources for mediatek devices are not bootable even if didn't give us any errors while compiling.

This is a basic compilation for newbies, so this article should work with 75% of the users who like to use APatch.

Users should know some crucial parts like about git, Linux commands etc to make a bootable kernel.

Thank you 😊
